When staging, check if token has necessary permission. Fixes #79.

diff --git a/ada/ada b/ada/ada
--- a/ada/ada
+++ b/ada/ada
@@ -781,6 +781,7 @@ validate_expiration_timestamp () {
 check_token() {
   local token="$1"
   local token_debug_info="$2"
+  local command="$3"
 
   # Determine token type (JWT or Macaroon)
   if [[ "$token" =~ ^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$ ]]; then
@@ -800,6 +801,31 @@ check_token() {
 
     # Fail if the token has (almost) expired
     validate_expiration_timestamp "$exp_unix" "$token_debug_info" || return 1
+
+    # If we're staging, the token must have storage.stage permission,
+    # or no storage.* claims at all.
+    # As of dCache 10.1, this is required.
+    if [[ "$command" == 'stage' ]] ; then
+      # For dCache, there are 2 kinds of OIDC tokens: those with storage.* claims,
+      # and those without any storage.* claims.
+      # If there is no storage.* claim at all, dCache will just assume
+      # everything is allowed.
+      # If there is at least one storage.* claim, dCache will check if the storage.* claims
+      # are sufficient for the job.
+      # So, we check if there is any storage claim.
+      oidc_scope=$(echo "$payload" | jq -r '.scope' 2>/dev/null)
+      if grep --silent 'storage\.' <<<"$oidc_scope" ; then
+        # Yes, there is a storage claim.
+        # This means we need storage.stage to be allowed to stage!
+        if ! grep --silent 'storage\.stage' <<<"$oidc_scope" ; then
+          echo 1>&2 "ERROR: You want to stage data from tape, but your OIDC token" \
+                    "does not have the storage.stage permission in its scope." \
+                    "You can check this with the --viewtoken option." \
+                    "Please use an OIDC token with 'storage.stage' in its scope."
+          return 1
+        fi
+      fi
+    fi
 
     # If we get here, it means we have a valid OIDC token.
     $debug && echo "$payload" | jq '. | .exp |= todate | .nbf |= todate | .iat |= todate'
@@ -848,6 +874,18 @@ check_token() {
 
     # Fail if the token has (almost) expired
     validate_expiration_timestamp "$exp_unix" "$token_debug_info" || return 1
+
+    # If we're staging, the macaroon must have STAGE activity permission.
+    # As of dCache 10.1, the STAGE activity is required for staging with a macaroon.
+    if [[ "$command" == 'stage' ]] ; then
+      if ! grep --silent 'activity:.*STAGE' <<<"$macaroon_decoded" ; then
+        echo 1>&2 "ERROR: You want to stage data from tape, but your macaroon token" \
+                  "does not have the STAGE activity permission." \
+                  "You can check this with the --viewtoken option." \
+                  "Please use a macaroon with the STAGE activity permission."
+        return 1
+      fi
+    fi
 
     # If we get here, it means we have a valid macaroon.
     $debug && echo -e "\033[34m\n$macaroon_decoded\n\033[0m" | sed -e 's/^/  /'
@@ -1806,7 +1844,9 @@ validate_input() {
       # Token should be valid - unless we want to view the token!
       # We should be able to view also invalid tokens (to check what's wrong with them).
       if [[ $command != 'viewtoken' ]] ; then
-        check_token "$token" "$token_debug_info" || exit 1
+        # We also send the command, so we can check if the token
+        # has the necessary permissions for the job.
+        check_token "$token" "$token_debug_info" "$command" || exit 1
       fi
       ;;
     netrc )
