To check if parent dir exists, use /namespace call instead of /tape/locality (#106)
* To check if parent dir exists, use /namespace call instead of /tape/locality

Fixes #105

* Fix unit test
* New function is_dir() interfered with the output of create_path()
* Typo was fixed in ada but should be fixed in unit test as well, to match

* Removing `get_locality` function
* The function used the /tape API call to check whether an object existed. This is not the best call to do that; the namespace call is better for that. Also, there has been a recent change in dCache that affects how this API call works, breaking Ada.
* The last remaining call to this function was not really necessary, because the `case` statement below it already catches the case where a path does not exist.
* Not using `is_dir` because the path might be a file... `is_dir` only returns true for a directory.

* Fix integration test: use is_dir in test_ada_mkdir instead of get_locality

---------

Co-authored-by: Haili Hu <hailihu@gmail.com>

diff --git a/ada/ada b/ada/ada
--- a/ada/ada
+++ b/ada/ada
@@ -1100,6 +1100,22 @@ pathtype () {
 }
 
 
+is_dir () {
+  # Check whether a path is a directory. If the path doesn't exist, just continue.
+  # Similar to pathtype(), but that one quits with error if the path doesn't exist.
+  encoded_path=$(urlencode "$1")
+  result=$(
+            $debug && set -x
+            curl "${curl_authorization[@]}" \
+                 -H "accept: application/json" \
+                 --silent \
+                 -X GET "$api/namespace/$encoded_path" 2>/dev/null
+          )
+  # The exit code of the grep will be passed on to the calling statement.
+  echo "$result" | jq -r .fileType | grep --silent 'DIR'
+}
+
+
 get_pnfsid () {
   local path=$(urlencode "$1")
   command='curl "${curl_authorization[@]}" \
@@ -1313,19 +1329,21 @@ create_path () {
   local path="$1"
   local recursive="$2"
   local parent="$(dirname "$path")"
-  get_locality "$parent"
-  error=$?
-  if [ $error == 1 ] && $recursive ; then
-    if [ "${#parent}" -gt 1 ]; then
-      echo 1>&2 "Warning: parent dir '$parent' does not exist. Will atempt to create it."
-      create_path "$parent" "$recursive"
+  if ! is_dir "$parent" ; then
+    # The parent dir does not exist yet. Should we create it?
+    if $recursive ; then
+      if [ "${#parent}" -gt 1 ]; then
+        echo 1>&2 "Warning: parent dir '$parent' does not exist. Will attempt to create it."
+        create_path "$parent" "$recursive"
+      else
+        # We reached the root dir. Something most be wrong.
+        echo 1>&2 "ERROR: Unable to create dirs. Check the specified path."
+        exit 1
+      fi
     else
-      echo 1>&2 "ERROR: Unable to create dirs. Check the specified path."
+      echo 1>&2 "ERROR: parent dir '$parent' does not exist. To recursively create dirs, add --recursive."
       exit 1
     fi
-  elif [ $error == 1 ]; then
-    echo 1>&2 "ERROR: parent dir '$parent' does not exist. To recursivly create dirs, add --recursive."
-    exit 1
   fi
   parent=$(urlencode "$(dirname "$path")")
   name=$(basename "$path")
@@ -1393,36 +1411,12 @@ delete_path () {
 }
 
 
-get_locality () {
-  local path="$1"
-  locality="$( (\
-    $debug && set -x   # If --debug is specified, show curl & jq command
-    curl "${curl_authorization[@]}" \
-         "${curl_options_common[@]}" \
-         "${curl_options_post[@]}" \
-         -X POST "$api/tape/archiveinfo" \
-         -d "{\"paths\":[\"/${path}\"]}" \
-  ) | jq . | grep locality)"
-  if [ -z "$locality" ] ; then
-    return 1
-  else
-    return 0
-  fi
-}
-
-
 bulk_request() {
   local activity="$1"
   local pathlist="$2"
   local recursive="$3"
   if [ "$from_file" == false ] ; then
     local filepath="$2"
-    get_locality "$filepath"
-    error=$?
-    if [ "$error" == 1 ] ; then
-      echo 1>&2 "Error: '$filepath' does not exist."
-      exit 1
-    fi
     type=$(pathtype "$filepath")
     case $type in
       DIR )
@@ -2317,6 +2311,10 @@ api_call () {
       )
       ;;
     mkdir )
+      if is_dir "$path" ; then
+        echo 1>&2 "Directory '$path' already exists."
+        exit 0
+      fi
       create_path "$path" "$recursive"
       ;;
     mv )
