New --whoami and --mkdir commands

diff --git a/ada/ada b/ada/ada
--- a/ada/ada
+++ b/ada/ada
@@ -2,6 +2,8 @@
 
 # This script talks to the dCache API.
 #
+# Design: Natalie & Onno, SURFsara.
+#
 # Latest version is available at: https://github.com/sara-nl/SpiderScripts
 #
 # Changes:
@@ -55,6 +57,10 @@ while [ $# -gt 0 ] ; do
       api="$2"
       shift 2
       ;;
+    --whoami )
+      command=whoami
+      shift
+      ;;
     --list )
       command=list
       path="$2"
@@ -62,6 +68,11 @@ while [ $# -gt 0 ] ; do
       ;;
     --longlist )
       command=longlist
+      path="$2"
+      shift 2
+      ;;
+    --mkdir )
+      command=mkdir
       path="$2"
       shift 2
       ;;
@@ -78,25 +89,59 @@ done
 
 if [ -z "$token" ] ; then
   if [ -n "$tokenfile" ] ; then
-    token=$(grep 'bearer_token *= *\w' "$tokenfile" | sed -e 's/bearer_token *= *//')
+    token=$(sed -n 's/^bearer_token *= *//p' "$tokenfile")
+    if [ $(wc -l <<<"$token") -gt 1 ] ; then
+      echo "ERROR: file '$tokenfile' contains multiple tokens."
+      exit 1
+    fi
     if [ -z "$token" ] ; then
       echo "ERROR: could not read token from tokenfile."
+      exit 1
     fi
   else
     echo "ERROR: no token or tokenfile specified."
+    exit 1
   fi
 fi
 
-$debug && echo "Token: '$token'"
+#$debug && echo "Token: '$token'"
 
 curl_authorization=( "-H" "Authorization: Bearer $token" )
-$debug && echo "${curl_authorization[@]}"
+#$debug && echo "${curl_authorization[@]}"
 
 case $command in
+  list | longlist | mkdir )
+    if [[ -z $path || $path =~ ^-- ]] ; then
+      echo "ERROR: command $command requires a path."
+      exit 1
+    fi
+    ;;
+esac
+
+
+
+case $command in
+  whoami )
+    $debug && {
+        echo -n "curl "
+        printf '"%s" '  "${curl_authorization[@]}"
+        echo -n "-X GET \"$api/user\" "
+        echo    "-H  \"accept: application/json\" --fail --silent --show-error"
+        echo
+    }
+    curl "${curl_authorization[@]}" \
+         -X GET "$api/user" \
+         -H  "accept: application/json" --fail --silent --show-error \
+    | jq
+    ;;
   list )
-    $debug && echo "curl \"${curl_authorization[@]}\" \
-         -X GET \"$api/namespace/$path?children=true&locality=false&locations=false&qos=false\" \
-         -H  \"accept: application/json\" --fail --silent --show-error"
+    $debug && {
+        echo -n "curl "
+        printf '"%s" '  "${curl_authorization[@]}"
+        echo -n "-X GET \"$api/namespace/$path?children=true&locality=false&locations=false&qos=false\" "
+        echo    "-H  \"accept: application/json\" --fail --silent --show-error"
+        echo
+    }
     curl "${curl_authorization[@]}" \
          -X GET "$api/namespace/$path?children=true&locality=false&locations=false&qos=false" \
          -H  "accept: application/json" --fail --silent --show-error \
@@ -104,12 +149,17 @@ case $command in
     | sed -e 's/^"//' \
           -e 's/",/,/' \
           -e 's/,"REGULAR"//' \
-          -e 's@,"DIR"@/@'
+          -e 's@,"DIR"@/@' \
+    | sort
     ;;
   longlist )
-    $debug && echo "curl \"${curl_authorization[@]}\" \
-         -X GET \"$api/namespace/$path?children=true&locality=false&locations=false&qos=false\" \
-         -H  \"accept: application/json\" --fail --silent --show-error"
+    $debug && { 
+        echo -n "curl " 
+        printf '"%s" ' "${curl_authorization[@]}"
+        echo -n "-X GET \"$api/namespace/$path?children=true&locality=false&locations=false&qos=false\" "
+        echo    "-H  \"accept: application/json\" --fail --silent --show-error"
+        echo
+    }
     curl "${curl_authorization[@]}" \
          -X GET "$api/namespace/$path?children=true&locality=false&locations=false&qos=false" \
          -H  "accept: application/json" --fail --silent --show-error \
@@ -120,7 +170,20 @@ case $command in
     | sed -e 's/^"//' \
           -e 's/"$//' \
           -e 's/","//g' \
-          -e 's/"20/20/'
+          -e 's/"20/20/' \
+    | sort
+    # Note: it would be better to use strflocaltime instead of strftime,
+    # but that requires a newer version of jq than Centos 7 has.
+    ;;
+  mkdir )
+    parent=$(dirname "$path")
+    name=$(basename "$path")
+    curl "${curl_authorization[@]}" \
+         -X POST "$api/namespace/$parent" \
+         -H "accept: application/json" \
+         -H "content-type: application/json" \
+         -d "{ \"action\":\"mkdir\";\"name\":\"$name\"}" --fail --silent --show-error \
+    | jq -r .status
     ;;
   * )
     echo "Command $command is not implemented (yet)."
