Added option stat-request to get status of bulk request for given request-id

diff --git a/ada/ada b/ada/ada
--- a/ada/ada
+++ b/ada/ada
@@ -183,6 +183,9 @@ usage() {
 	  --unstage --from-file <file-list>
 	      Release files in the list.
 
+    --stat-request <request-id>
+	      Show status of bulk request for given request-id
+
 	  --events <channel-name> <path-to-follow> [--resume] [--force] [--recursive] [--timeout s]
 	      Subscribe to changes in the given direcory,
 	      using server-sent events (SSE).
@@ -613,7 +616,12 @@ get_args() {
       --request-id )
         request_id="$2"
         shift ; shift
-        ;;        
+        ;;
+      --stat-request )
+        command='stat-request'
+        request_id="$2"
+        shift ; shift
+        ;;  
       --events )
         command='events'
         channel_name="$2"
@@ -2294,6 +2302,12 @@ validate_input() {
         exit 1
       fi
       ;;
+    stat-request )
+      if [[ -z $request_id || $request_id =~ ^-- ]] ; then
+        echo 1>&2 "ERROR: command $command requires a request-id."
+        exit 1
+      fi
+      ;;    
     viewtoken )
       if [ -z "$token" ] ; then
         echo 1>&2 "ERROR: command --viewtoken requires a token, but no token was found."
@@ -2792,6 +2806,9 @@ api_call () {
         unstage )  activity='UNPIN'   ;;
       esac
       bulk_request "$activity" "$pathlist" "$recursive" "$request_id"
+      ;;
+    stat-request )
+      get_status_requestid "$request_id"
       ;;
     events | report-staged )
       if [ "${BASH_VERSINFO[0]}" -lt 4 ] ; then
