If channelname is not stored locally, --force needs to be added to resume

diff --git a/ada/ada b/ada/ada
--- a/ada/ada
+++ b/ada/ada
@@ -180,11 +180,13 @@ usage() {
 	  --unstage --from-file <file-list>
 	      Release files in the list.
 
-	  --events <channel-name> <path-to-follow> [--resume] [--recursive] [--timeout s]
+	  --events <channel-name> <path-to-follow> [--resume] [--force] [--recursive] [--timeout s]
 	      Subscribe to changes in the given direcory,
 	      using server-sent events (SSE).
-	      If channel-name is already in use, you must add --resume
+	      If channel name is already in use, you must add --resume
 	      to resume following this channel. 
+        If the channel name is not stored locally, you must also 
+        add --force to resume,
 	      When --recursive is added, all subdirectories will be
 	      followed as well, including any new subdirectories
 	      that will be created.
@@ -193,11 +195,13 @@ usage() {
 	      after this timeout. Events that have not been processed
 	      will then be lost.
 
-	  --report-staged <channel-name> <path-to-follow> [--resume] [--recursive] [--timeout s]
+	  --report-staged <channel-name> <path-to-follow> [--resume] [--force] [--recursive] [--timeout s]
 	      Subscribe to stage (bring online) events in a directory,
 	      using server-sent events (SSE).
-	      If channel-name is already in use, you must add --resume
-	      to resume following this channel. 
+	      If channel name is already in use, you must add --resume
+	      to resume following this channel.
+        If the channel name is not stored locally, you must also 
+        add --force to resume,
 	      This command is slightly different from --events:
 	      When you start it, all files in the scope will be listed,
 	      including their locality and QoS. This allows your event
@@ -2402,6 +2406,7 @@ api_call () {
         exit 1
       fi
       channel=$(get_channel_by_name "$channelname")
+      channel_id=$(basename "$channel")
       if [ "$channel" = "" ] ; then
         # Channel doesn't exist; create it.
         (
@@ -2411,10 +2416,8 @@ api_call () {
                "${curl_options_post[@]}" \
                -X POST "$api/events/channels" -d "{\"client-id\":\"$channelname\"}"
         )
-        channel=$(get_channel_by_name "$channelname")
         # There is no API call to translate channel ID back to
         # channel name. So we keep track of the name ourselves.
-        channel_id=$(basename "$channel")
         echo "$channelname" > "${ada_dir}/channels/channel-name-${channel_id}"
         # Set channel timeout
         (
@@ -2426,7 +2429,12 @@ api_call () {
                -d "{\"timeout\": $channel_timeout}"
         )
       elif ! $resume ; then
+        # Channel already exists; add --resume to continue
         echo 1>&2 "ERROR: channel name '$channelname' is already used. To resume following this channel, add  --resume."
+        exit 1
+      elif [ ! -f "${ada_dir}/channels/channel-name-${channel_id}" ] && ! $force ; then
+        # Channel already exists but channelname was not saved locally; add --resume and --force to continue      
+        echo 1>&2 "ERROR: channel name '$channelname' is already used but was not saved locally. Add --force if you still want to resume."
         exit 1
       fi
       echo "Channel: $channel"
