Check if file or directory exists before staging

diff --git a/ada/ada b/ada/ada
--- a/ada/ada
+++ b/ada/ada
@@ -201,6 +201,7 @@ auth_method=
 certdir=${X509_CERT_DIR:-/etc/grid-security/certificates}
 lifetime=7
 lifetime_unit=DAYS
+from_file=false
 
 # Default options to curl for various activities;
 # these can be overidden in configuration files, see below.
@@ -366,9 +367,11 @@ while [ $# -gt 0 ] ; do
     --stage )
       command='stage'
       if [[ $2 =~ ^--from-?file ]] ; then
+        from_file=true
         pathlist=$(<"$3")
        	shift ;	shift ;	shift
       else
+        from_file=false
         pathlist="$2"
         shift ; shift
       fi
@@ -376,9 +379,11 @@ while [ $# -gt 0 ] ; do
     --unstage )
       command='unstage'
       if [[ $2 =~ ^--from-?file ]] ; then
+        from_file=true
         pathlist=$(<"$3")
         shift ; shift ; shift
       else
+        from_file=false
         pathlist="$2"
         shift ; shift
       fi
@@ -834,6 +839,27 @@ delete_path () {
 }
 
 
+get_locality () {
+  local path="$1"
+  # encoded_path=$(urlencode "$path")
+  $debug || echo -n "$file  "
+  locality="$((\
+    $debug && set -x   # If --debug is specified, show (only) curl command
+    curl "${curl_authorization[@]}" \
+         "${curl_options_common[@]}" \
+         "${curl_options_post[@]}" \
+         -X POST "$api/tape/archiveinfo" \
+         -d "{\"paths\":[\"/${path}\"]}" \
+  ) | jq . | grep locality)"
+  if [ -z "$locality" ] ; then
+    return 1
+  else
+    echo "exists"
+    return 0
+  fi
+}
+
+
 bulk_request() {
   local path="$1"
   local recursive="$2"
@@ -857,7 +883,6 @@ bulk_request() {
       ;;
   esac
   arguments="{\"lifetime\": \"${lifetime}\", \"lifetimeUnit\":\"${lifetime_unit}\"}, \"target\": [\"/${path}\"], \"expand_directories\": \"${expand}\"}"
-  encoded_path=$(urlencode "$path")
   $debug || echo -n "$path  "
   (
     $debug && set -x   # If --debug is specified, show (only) curl command 
@@ -1417,6 +1442,14 @@ case $command in
     done <<<"$pathlist"
     ;;
   stage )
+    if [ "$from_file" == false ] ; then
+        get_locality "$pathlist"
+        error=$?
+        if [ "$error" == 1 ] ; then
+          echo 1>&2 "Error: '$pathlist' does not exist."
+          exit 1
+        fi
+    fi
     while read -r path ; do
       bulk_request "$path" "$recursive"
     done <<<"$pathlist" \
