102 do not create channel if folder does not exist (#108)
* To check if parent dir exists, use /namespace call instead of /tape/locality

Fixes #105

* Fix unit test
* New function is_dir() interfered with the output of create_path()
* Typo was fixed in ada but should be fixed in unit test as well, to match

* Improve validation for --events and --report-staged
* Ada now checks whether a valid, existing directory is provided
* The order of validation has changed to provide more accurate error messages. When the channel name is missing, Ada will not say the path is missing, but say that the channel name and directory are missing (because if there's no channel name, the path must be missing as well)

* Do path validation after construct_auth()
Because the path validation calls the API and this will fail when the authentication has not been set up.

* Exit when is_dir is used before construct_auth
This should prevent us developers from making this mistake again.

* Fix unit test to match changed output in previous commit

* Fix comment

* Adapt unit test for create_path

---------

Co-authored-by: Haili Hu <hailihu@gmail.com>

diff --git a/ada/ada b/ada/ada
--- a/ada/ada
+++ b/ada/ada
@@ -1130,6 +1130,12 @@ is_dir () {
   # Check whether a path is a directory. If the path doesn't exist, just continue.
   # Similar to pathtype(), but that one quits with error if the path doesn't exist.
   encoded_path=$(urlencode "$1")
+  # Warn the developers not to call is_dir before the auth has been set up.
+  if [ -z "$curl_authorization" ] ; then
+    echo 1>&2 "ERROR: calling function is_dir() before authentication has been set up." \
+              "Please submit an issue for this at https://github.com/sara-nl/SpiderScripts/ ."
+    exit 1
+  fi
   result=$(
             $debug && set -x
             curl "${curl_authorization[@]}" \
@@ -2160,8 +2166,7 @@ validate_input() {
   case $command in
     list | stat | mkdir | mv | delete | \
     setlabel | lslabel | findlabel | rmlabel | \
-    setxattr | lsxattr | findxattr | rmxattr | \
-    events | report-staged )
+    setxattr | lsxattr | findxattr | rmxattr )
       if [[ -z $path || $path =~ ^-- ]] ; then
         echo 1>&2 "ERROR: command $command requires a path."
         exit 1
@@ -2215,13 +2220,17 @@ validate_input() {
             exit 1
           fi
           ;;
-        events | report-staged )
-          if [[ -z $channel_name || $channel_name =~ ^-- ]] ; then
-            echo 1>&2 "ERROR: command $command requires a channel name."
-            exit 1
-          fi
-          ;;
       esac
+      ;;
+    events | report-staged )
+      if [[ -z $channel_name || $channel_name =~ ^-- ]] ; then
+        echo 1>&2 "ERROR: command $command requires a channel name and a directory."
+        exit 1
+      fi
+      if [[ -z $path || $path =~ ^-- ]] ; then
+        echo 1>&2 "ERROR: command $command requires a directory."
+        exit 1
+      fi
       ;;
     longlist | checksum | stage | unstage )
       if [[ -z $pathlist || $pathlist =~ ^-- ]] ; then
@@ -2743,6 +2752,13 @@ api_call () {
         esac
         exit 1
       fi
+      # Some additional input validation, after construct_auth().
+      # We need an existing directory.
+      if ! is_dir "$path" ; then
+        echo 1>&2 "ERROR: '$path' is not a directory."
+        exit 1
+      fi
+      # Setting up channel
       channel_url=$(get_channel_by_name "$channel_name")
       channel_id=$(basename "$channel_url")
       if [ "$channel_url" = "" ] ; then
